In [4]:
import numpy as np

In [5]:
v = np.arange(12).reshape(3,4)
print(v)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
#multidimensional array
v = np.arange(15).reshape(3,5)
v

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
v[1,1]

6

In [13]:
v[0:4,0:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [14]:
v[:,2]

array([ 2,  7, 12])

In [17]:
v = v.flatten()
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [19]:
for r in v:
    print(r)
v = np.arange(15).reshape(3,5)
print(v)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [21]:
for e in v.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [22]:
#copying arrays
s = np.arange(10)
print(s)


[0 1 2 3 4 5 6 7 8 9]


In [24]:
b = s
b is s

True

In [25]:
b.shape = (2, 5)
print(b)
s.shape

[[0 1 2 3 4]
 [5 6 7 8 9]]


(2, 5)

In [26]:
b is s

True

In [27]:
print(s)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:
s = np.arange(12)
b = s[:]
s.shape = (3,4)

print(s)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [30]:
b[1] = -1
print(s)
print(b)

[[ 0 -1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0 -1  2  3  4  5  6  7  8  9 10 11]


In [31]:
d = b[3:8]
print(b)

[ 0 -1  2  3  4  5  6  7  8  9 10 11]


In [32]:
d[:] = 0 

In [33]:
print(s)
print(b)
print(d)

[[ 0 -1  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]
[ 0 -1  2  0  0  0  0  0  8  9 10 11]
[0 0 0 0 0]


In [34]:
print(b is s)
print(b.base is s)
print(b.flags.owndata)
print(s.flags.owndata)

False
True
False
True


In [35]:
d = s.copy()
d[:,:] = 0.0

print(s)
print(d)

[[ 0 -1  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [36]:
#boolean indexing
s = np.arange(12).reshape(3,4)
s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
s[s > 4] = 0
s

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [38]:
s[s == 0] = -1
s

array([[-1,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [39]:
s==-1

array([[ True, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
s = np.arange(12).reshape(3,4)
s[np.logical_and(s > 3, s <= 9)] = 0.0
s

array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 0,  0, 10, 11]])

In [41]:
s>4

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [42]:
#avoidind loops
p=32
q=64
xmin=ymin=0.0
xmax=ymax=1.0

m= np.linspace(xmin, xmax, p, endpoint=False)
n= np.linspace(ymin, ymax, q, endpoint=False)

print(m.shape)
print(n.shape)
n

(32,)
(64,)


array([0.      , 0.015625, 0.03125 , 0.046875, 0.0625  , 0.078125,
       0.09375 , 0.109375, 0.125   , 0.140625, 0.15625 , 0.171875,
       0.1875  , 0.203125, 0.21875 , 0.234375, 0.25    , 0.265625,
       0.28125 , 0.296875, 0.3125  , 0.328125, 0.34375 , 0.359375,
       0.375   , 0.390625, 0.40625 , 0.421875, 0.4375  , 0.453125,
       0.46875 , 0.484375, 0.5     , 0.515625, 0.53125 , 0.546875,
       0.5625  , 0.578125, 0.59375 , 0.609375, 0.625   , 0.640625,
       0.65625 , 0.671875, 0.6875  , 0.703125, 0.71875 , 0.734375,
       0.75    , 0.765625, 0.78125 , 0.796875, 0.8125  , 0.828125,
       0.84375 , 0.859375, 0.875   , 0.890625, 0.90625 , 0.921875,
       0.9375  , 0.953125, 0.96875 , 0.984375])

In [43]:
import time
import numpy as np
p=32
q=64
m = np.linspace(0.0, 1.0, p, endpoint=False)
n = np.linspace(0.0, 1.0, q, endpoint=False)


In [45]:
t0 = time.time()
d=np.zeros((p,q))
for i in range(p):
    for j in range(q):
        d[i,j] = np.sin(2.0*np.pi*m[i]*n[j])
        
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.011984109878540039 s


In [46]:
x2,y2 = np.meshgrid(m,n, indexing="ij")

print(x2[:,0])
print(x2[0,:])

print(y2[:,0])
print(y2[0,:])

[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.1875   0.203125 0.21875  0.234375
 0.25     0.265625 0.28125  0.296875 0.3125   0.328125 0.34375  0.359375
 0.375    0.390625 0.40625  0.421875 0.4375   0.453125 0.46875  0.484375
 0.5      0.515625 0.53125  0.546875 0.5625   0.578125 0.59375  0.609375
 0.625    0.640625 0.65625  0.671875 0.6875   0.703125 0.71875  0.734375
 0.75     

In [48]:
t0=time.time()
d2=np.sin(2.0*np.pi*x2*y2)
t1=time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.0 s


In [49]:
#concatenation of arrays
a=np.array([1, 2, 3, 4])
b=np.array([4, 3, 2, 1])
np.concatenate([b,a])

array([4, 3, 2, 1, 1, 2, 3, 4])

In [50]:
c=[9, 4, 6]
print(np.concatenate([a,b,c]))

[1 2 3 4 4 3 2 1 9 4 6]


In [51]:
g=np.array([[10, 20, 30],
                 [40, 50, 60]])

In [52]:
np.concatenate([g,g])

array([[10, 20, 30],
       [40, 50, 60],
       [10, 20, 30],
       [40, 50, 60]])

In [53]:
np.concatenate([g,g], axis=1)

array([[10, 20, 30, 10, 20, 30],
       [40, 50, 60, 40, 50, 60]])

In [55]:
#splitting of arrays
a=[1, 2, 3, 4, 4, 3 ,2, 1, 9, 4 ,6]
a1,a2,a3,a4=np.split(a,[3, 5,8])
print(a1,a2,a3,a4)

[1 2 3] [4 4] [3 2 1] [9 4 6]


In [56]:
g = np.arange(25).reshape((5, 5))
g

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
l,r = np.hsplit(g,[2])
print(l)
print(r)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


In [59]:
#aggregates
a=np.arange(1, 9)
print(a)
np.add.reduce(a)

[1 2 3 4 5 6 7 8]


36

In [60]:
np.multiply.reduce(a)

40320

In [61]:
np.add.accumulate(a)

array([ 1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [63]:
np.multiply.accumulate(a)

array([    1,     2,     6,    24,   120,   720,  5040, 40320],
      dtype=int32)